- hosts: RASPI_WIFI
  remote_user: pi
  become: yes
  become_method: sudo
  become_user: root

  vars:
    domain_name: cthulhuuuu.iot
    dns_servers: 8.8.8.8, 8.8.4.4, 130.223.4.5, 130.223.8.20, 172.21.20.10, 172.21.20.11
    wlan_interface: wlan0
    ssid_name: ESC-IoT
    wpa_passphrase: esc_iot_2018

  tasks:
    - name: ensure linux-igd (upnpd) is at the latest version
      apt: name=linux-igd state=latest

    - name: copy upnp systemd unit
      template: src=upnpd.service dest=/etc/systemd/system/upnpd.service
      notify:
        - restart upnpd

    - name: ensure upnpd is running and enable at boot
      service: name=upnpd state=started enabled=yes

  handlers:
    - name: restart upnpd
      service: name=upnpd state=restarted
