- hosts: RASPI_WIFI
  remote_user: pi
  become: yes
  become_method: sudo
  become_user: root

  vars:
    wlan_interface: wlan0

  tasks:
    - name: Creates tcpdump pcap directory
      file:
        path: /var/tcpdump
        state: directory

    - name: ensure tcpdump is at the latest version
      apt: name=tcpdump state=latest

    - name: copy tcpdump systemd unit
      template: src=tcpdump.j2 dest=/etc/systemd/system/tcpdump.service
      notify:
        - reload systemctl

#    - name: ensure tcpdump is stopped and enable at boot
#      service: name=tcpdump state=restarted enabled=yes

  handlers:
    - name: reload systemctl
      shell:
        cmd: systemctl daemon-reload