- hosts: RASPI_WIFI
  remote_user: pi
  become: yes
  become_method: sudo
  become_user: root

  vars:
    domain_name: cthulhuuuu.iot
    dns_servers: 8.8.8.8, 8.8.4.4, 130.223.4.5, 130.223.8.20, 172.21.20.10, 172.21.20.11
    wlan_interface: wlan0
    ssid_name: ESC-IoT
    wpa_passphrase: esc_iot_2018

  tasks:
    - name: ensure mitmproxy is at the latest version
      apt: name=mitmproxy state=latest

    - name: copy mitmweb systemd unit
      template: src=mitmweb.service dest=/etc/systemd/system/mitmweb.service
      notify:
        - restart mitmweb

    - name: ensure mitmweb is running and enable at boot
      service: name=mitmweb state=started enabled=yes

  handlers:
    - name: restart mitmweb
      service: name=mitmweb state=restarted
