- hosts: RASPI_WIFI
  remote_user: pi
  become: yes
  become_method: sudo
  become_user: root

  vars:
    domain_name: cthulhuuuu.iot
    wlan_interface: wlan0
    ssid_name: Pi-Pineapple
    wpa_passphrase: Pi-Pineapple

  tasks:
    - name: ensure hostapd is at the latest version
      apt: name=hostapd state=latest
    - name: ensure dns & dhcp server is at the latest version
      apt: name=dnsmasq state=latest
    - name: ensure haveged (entropy generator) is at the latest version
      apt: name=haveged state=latest
    - name: ensure iptables-persistent is at the latest version
      apt: name=iptables-persistent state=latest

    - name: copy dhcpcd configuration file
      template: src=dhcpcd.j2 dest=/etc/dhcpcd.conf
    - name: restart Wlan interfaces
      command: bash -c "ifconfig {{ wlan_interface }} down && ifconfig {{ wlan_interface }} up"

    - name: copy hostapd psk file (for WPS)
      template: src=hostapd.psk dest=/etc/hostapd.psk
    - name: copy hostapd configuration file
      template: src=hostapd.j2 dest=/etc/hostapd/hostapd.conf
    - name: copy hostapd default configuration file
      template: src=hostapd.conf dest=/etc/default/hostapd.conf

    - name: copy dnsmasq configuration file
      template: src=dnsmasq.j2 dest=/etc/dnsmasq.conf

    - name: ensure hostapd is running and enable at boot
      service: name=hostapd state=restarted enabled=yes
    - name: ensure dnsmasq is running and enable at boot
      service: name=dnsmasq state=restarted enabled=yes

    - name: copy iptables configuration
      template: src=rules.v4.j2 dest=/etc/iptables/rules.v4
    - name: restore iptables
      command: iptables-restore /etc/iptables/rules.v4
    - name: ensure iptables-persistent (netfilter-persistent) is running and enable at boot
      service: name=netfilter-persistent state=started enabled=yes

    - name: ensure ip forwarding is enabled
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes
