- hosts: RASPI_WIFI
  remote_user: pi
  become: yes
  become_method: sudo
  become_user: root

  vars:
    domain_name: cthulhuuuu.iot
    dns_servers: 8.8.8.8, 8.8.4.4, 130.223.4.5, 130.223.8.20, 172.21.20.10, 172.21.20.11
    wlan_interface: wlan0
    ssid_name: ESC-IoT
    wpa_passphrase: esc_iot_2018

  tasks:
    - name: ensure git is at the latest version
      apt: name=git state=latest
    - name: ensure libssl-dev is at the latest version
      apt: name=libssl-dev state=latest
    - name: ensure libffi-dev is at the latest version
      apt: name=libffi-dev state=latest
    - name: ensure python3 is at the latest version
      apt: name=python3 state=latest
    - name: ensure pip3 is at the latest version
      apt: name=python3-pip state=latest
    - name: ensure setuptools is at the latest version
      apt: name=python-setuptools state=latest
    - name: ensure setuptools for python3 is at the latest version
      pip: name=setuptools executable=pip3

    - name: get mitmproxy 5.3.0  # 6+ drops support for python3.7 which is default on raspbian
      git: 
        repo: https://github.com/mitmproxy/mitmproxy
        dest: /opt/mitmproxy
        version: v5.3.0
        update: yes

    - name: build and install mitmproxy & dependencies
      shell: 
        cmd: python3 setup.py install
        chdir: /opt/mitmproxy

    - name: copy mitmweb systemd unit
      template: src=mitmweb.service dest=/etc/systemd/system/mitmweb.service
      notify:
        - reload systemctl

    - name: ensure mitmweb is running and enable at boot
      service: name=mitmweb state=restarted enabled=yes
  
  handlers:
    - name: reload systemctl
      shell: 
        cmd: systemctl daemon-reload